### ISSUE TITLE
Separate apps (tomoscan, tomomaster) to different file

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#53]
In testnet, we use 02apps.yml for all app (tomoscan, tomomaster, faucet, netstats, proxy)

I suggest we should separate them, e.g:
tomoscan -> tomoscan.yml
tomomater -> tomomaster.yml
proxy, netstats, ... -> others.yml

So when we update the stacks (docker stack deploy ..), they are independent, do not effect others.
Today, I tried to move tomoscan_redis to new server, I had to update/restart all services (tomomaster, tomoscan ..)

**Comment by etienne-napoleone** [comment]
Yep, could do!
Although, just to keep in mind:
- to update services, use `docker service update` 
- to remove services, use `docker service rm`
- to deploy new service, use `docker stack deploy`
- updating a service who hasn't changed does not trigger any action and would normally not cause any problems

If this creates unwanted update, it's because we're not yet pinning container versions where we should, separate issue

**Comment by etienne-napoleone** [comment]
related to https://github.com/tomochain/infrastructure/issues/54
